branch-defaults:
  default:
    environment: lyrify-dev
    group_suffix: null
global:
  application_name: lyrify
  default_ec2_keyname: sidharth6323
  default_platform: Python 2.7
  default_region: ap-southeast-1
  profile: eb-cli
  sc: null
